name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
    paths-ignore:
    - LICENSE
    - README.md
    - '**.md'
  pull_request:
    paths-ignore:
    - LICENSE
    - README.md
    - '**.md'

jobs:
  build-cpp:
    name: Build C++ (ExternalViewHelper)
    runs-on: ${{ matrix.os }}
    env:
        HL2SDKCS2: ${{ github.workspace }}/cs2-external-view/cpp-extv/extern/hl2sdk
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
          - os: ubuntu-latest
            container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: cs2-external-view
          submodules: recursive
          fetch-depth: 0

      - name: Checkout Metamod
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/metamod-source
          ref: master
          path: mmsource-2.0
          submodules: recursive

      - name: Checkout AMBuild
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      - name: Install AMBuild
        run: |
          cd ambuild && python setup.py install && cd ..

      - name: Install Clang 16
        if: matrix.os == 'ubuntu-latest'
        run: |
          apt update && apt install -y clang-16
          ln -sf /usr/bin/clang-16 /usr/bin/clang && ln -sf /usr/bin/clang++-16 /usr/bin/clang++

      - name: Setup vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $env:GITHUB_ENV

      - name: Build C++ (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: cs2-external-view/cpp-extv
        shell: bash
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
          cmake --build . --config Release
          cmake --install . --config Release --prefix ../install

      - name: Build C++ (Linux)
        if: matrix.os == 'ubuntu-latest'
        working-directory: cs2-external-view/cpp-extv
        shell: bash
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          make install DESTDIR=../install

      - name: Prepare artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p artifacts/cpp
          Copy-Item -Path "cs2-external-view/cpp-extv/install/bin/*" -Destination "artifacts/cpp/" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Prepare artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p artifacts/cpp
          cp -r cs2-external-view/cpp-extv/install/usr/local/bin/* artifacts/cpp/ 2>/dev/null || true
          cp -r cs2-external-view/cpp-extv/install/usr/local/lib/* artifacts/cpp/ 2>/dev/null || true

      - name: Upload C++ artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-cpp
          path: artifacts/cpp/

  build-csharp:
    name: Build C# (ExternalView Plugin)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            artifact-name: Windows-csharp
          - os: ubuntu-latest
            artifact-name: Linux-csharp

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        working-directory: cs-extv
        run: dotnet restore

      - name: Build
        working-directory: cs-extv
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: cs-extv
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish
        working-directory: cs-extv
        run: dotnet publish ExternalView/ExternalView.csproj --configuration Release --output ../artifacts/csharp/

      - name: Copy language files
        run: |
          mkdir -p artifacts/csharp/lang
          cp addons/counterstrikesharp/plugins/ExternalView/lang/* artifacts/csharp/lang/

      - name: Upload C# artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: artifacts/csharp/

  package:
    name: Package Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-cpp, build-csharp]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release packages
        run: |
          version=${GITHUB_REF#refs/tags/}
          
          # Create Windows package
          mkdir -p release/windows/addons/metamod
          mkdir -p release/windows/addons/counterstrikesharp/plugins/ExternalView
          mkdir -p release/windows/addons/externalviewhelper/gamedata
          
          # Copy Windows C++ binaries
          if [ -d "Windows-cpp" ]; then
            cp Windows-cpp/* release/windows/addons/externalviewhelper/ 2>/dev/null || true
          fi
          
          # Copy Windows C# plugin
          if [ -d "Windows-csharp" ]; then
            cp Windows-csharp/*.dll release/windows/addons/counterstrikesharp/plugins/ExternalView/ 2>/dev/null || true
            cp -r Windows-csharp/lang release/windows/addons/counterstrikesharp/plugins/ExternalView/ 2>/dev/null || true
          fi
          
          # Copy configuration files
          cp addons/metamod/externalviewhelper.vdf release/windows/addons/metamod/
          cp addons/externalviewhelper/gamedata/externalviewhelper.games.txt release/windows/addons/externalviewhelper/gamedata/
          
          # Create Linux package
          mkdir -p release/linux/addons/metamod
          mkdir -p release/linux/addons/counterstrikesharp/plugins/ExternalView
          mkdir -p release/linux/addons/externalviewhelper/gamedata
          
          # Copy Linux C++ binaries
          if [ -d "Linux-cpp" ]; then
            cp Linux-cpp/* release/linux/addons/externalviewhelper/ 2>/dev/null || true
          fi
          
          # Copy Linux C# plugin
          if [ -d "Linux-csharp" ]; then
            cp Linux-csharp/*.dll release/linux/addons/counterstrikesharp/plugins/ExternalView/ 2>/dev/null || true
            cp -r Linux-csharp/lang release/linux/addons/counterstrikesharp/plugins/ExternalView/ 2>/dev/null || true
          fi
          
          # Copy configuration files
          cp addons/metamod/externalviewhelper.vdf release/linux/addons/metamod/
          cp addons/externalviewhelper/gamedata/externalviewhelper.games.txt release/linux/addons/externalviewhelper/gamedata/
          
          # Create archives
          cd release
          if [ -d "windows" ]; then
            cd windows
            zip -r ../../cs2-external-view-${version}-windows.zip *
            cd ..
          fi
          
          if [ -d "linux" ]; then
            cd linux
            tar -czf ../../cs2-external-view-${version}-linux.tar.gz *
            cd ..
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cs2-external-view-*.zip
            cs2-external-view-*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}